apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3-tire-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 3-tire-web-app
  template:
   metadata:
     labels:
       app: 3-tire-web-app
  containers:
  - name: 3-tire-web-app_webapp
    image: 643370628328.dkr.ecr.us-east-2.amazonaws.com/3-tire-web-app_webapp:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 3000

  - name: 3-tire-web-app_api 
    image: 643370628328.dkr.ecr.us-east-2.amazonaws.com/3-tire-web-app_api:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 3001
      
  - name: postgres  
    image: 643370628328.dkr.ecr.us-east-2.amazonaws.com/postgress:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 5432   
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: 3-tire-web-app
  #namespace: default #TODO: Make the namespace parameterized.
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: 3-tire-web-app
  minReplicas: 1 # TODO: Update the no of minReplicas
  maxReplicas: 1 # TODO: Update the no of maxReplicas
  targetCPUUtilizationPercentage: 80
     
