apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: LoadBalancer
  ports:
  - name: 3-tire-web-app
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: 3-tire-web-app
